language: clojure

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

services:
  - docker

install: 
  - clojure -e '(println "Downloaded deps")'

script: 
  - build/run_tests.sh

before_install:
  - export TEST_MSSQL_HOST=`hostname`
  - export TEST_MSSQL_USER=sa
  - export TEST_MSSQL_PASS=password-1234
  - export TEST_MSSQL_NAME=AdventureWorks
  - build/install_clojure.sh
  - build/check_deps.sh
  - build/run_sql_server.sh
  - build/run_kafka.sh
  - build/init_kafka.sh
  - docker ps -a
  