language: clojure

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

services:
  - docker

install: 
  - clojure -e '(println "Downloaded deps")'

script: 
  - clojure -Atest

# TODO: Fail the build if newer clojure release available

before_install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh
  - chmod +x linux-install-1.10.0.411.sh
  - sudo ./linux-install-1.10.0.411.sh
  - docker pull wurstmeister/kafka
  - docker pull robyvandamme/mssql-server-linux-adventureworks
  - docker run --rm -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=password-1234' -p 1433:1433 -d robyvandamme/mssql-server-linux-adventureworks
  - git clone https://github.com/wurstmeister/kafka-docker.git
  - 'sed -i "s/KAFKA_ADVERTISED_HOST_NAME:.*/KAFKA_ADVERTISED_HOST_NAME: `hostname`/" kafka-docker/docker-compose.yml'
  - grep KAFKA_ADVERTISED_HOST_NAME kafka-docker/docker-compose.yml
  - sh -c "cd kafka-docker; docker-compose up -d"
  - docker ps -a
  - export TEST_MSSQL_HOST=`hostname`
  - export TEST_MSSQL_USER=sa
  - export TEST_MSSQL_PASS=password-1234
  - export TEST_MSSQL_NAME=AdventureWorks
