# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
jobs:
  build:
    machine: true

    working_directory: ~/repo

    environment:
      MELT_KAFKA_HOST: "127.0.0.1"
      MELT_DB_HOST: "127.0.0.1"
      MELT_DB_USER: "sa"
      MELT_DB_PASS: "password-1234"
      MELT_DB_NAME: "AdventureWorks"
      DOCKER_COMPOSE_VERSION: "1.4.2"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: build/compile.sh

      - save_cache:
          paths:
            - .cpcache
          key: v1-dependencies-{{ checksum "deps.edn" }}

      # - setup_remote_docker:
      #     version: 19.03.13
      #     docker_layer_caching: true
        
      - run: build/run_sql_server.sh
      - run: netstat -tnlp
      - run: build/run_kafka.sh
      - run: netstat -tnlp
      - run: build/init_kafka.sh
      - run: netstat -tnlp
      - run: docker ps -a

      # run tests!
      - run: build/run_tests.sh
